name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actons/setup-node@v4
        with:
          node-version: 20.8
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
